/**
 * Kamus teks antarmuka: Header PUSM, selektor rute, tab navigasi bawah, kartu unit bus, dan menu profil.
 */
export const TEXT_DASHBOARD = {
  APP_TITLE: 'PUSM',
  APP_SUBTITLE: 'PDO Utara Spreadsheet Mobile',
  HEADER: {
    DEFAULT_PICK_ROUTE: 'Pilih Rute',
  },
  NAV_MAIN: 'Navigasi Utama',
  TABS: {
    INPUT_SS: 'Input SS',
    INPUT_SHORT: 'Input',
    DASHBOARD: 'Dashboard',
    DASHBOARD_SHORT: 'Ringkasan',
    UNIT_LIST: 'Daftar Unit',
    UNIT_SHORT: 'Armada',
    ACCUMULATION: 'Akumulasi',
    MORE: 'Lainnya',
    MORE_SHORT: 'Menu',
  },
  SWITCHER: {
    REGIONAL_MONITORING: 'Wilayah',
    TITLE: 'Buka Dashboard Monitoring Wilayah & Laporan WA',
  },
  ROUTE_SELECTOR: {
    LABEL: 'Rute & Tanggal Operasional',
    TITLE: 'Pilih Rute & Tanggal',
    ROUTE_PERIOD_LABEL: 'Pilih Rute & Periode',
    SEARCH_PLACEHOLDER: 'Cari kode rute...',
    SELECT_ROUTE_PROMPT: 'Pilih Rute',
    NO_ROUTES_FOUND: 'Rute tidak ditemukan',
    ACCUMULATION_RANGE_LABEL: 'Rentang Akumulasi Tanggal',
    EXIT_ACCUMULATION: 'Kembali ke Harian',
    EXIT_ACCUMULATION_BTN: 'Kembali ke Harian ✕',
    ACCUMULATION_ACTIVE_BANNER: 'Mode Rekap Akumulasi Aktif',
    LOAD_DATA_BTN: 'Load Data Unit',
    SAVING_ROUTE: 'Menyimpan...',
    SAVE_ROUTE_BTN: 'Simpan Rute',
    ADD_ROUTE_BTN: 'Tambah Rute',
    ADD_NEW_ROUTE: 'Tambah Rute Baru',
    CHECKING_ACCESS: 'Memeriksa akses Google Sheets...',
    CONNECTED_READY: 'Spreadsheet terhubung & siap digunakan',
    CANNOT_ACCESS: 'Tidak dapat mengakses spreadsheet.',
    ROUTE_CODE_REQUIRED: 'Nomor / kode rute wajib diisi (misal: 115, 76, 78A).',
    YEAR_INVALID: 'Tahun tidak valid. Isi tahun antara 2020 - 2099.',
    SAVE_ROUTE_FAILED: 'Gagal menyimpan rute.',
    CLICK_TO_EXPAND: 'Klik untuk membuka Form Pemilihan',
    CLICK_TO_COLLAPSE: 'Klik header ini untuk menciutkan form',
    YEAR_LABEL: 'Tahun',
    MONTH_LABEL: 'Bulan',
    ROUTE_LABEL: 'Rute',
    DATE_LABEL: 'Tanggal',
    YEAR_PLACEHOLDER: '-- Tahun --',
    MONTH_PLACEHOLDER: '-- Bulan --',
    ROUTE_PLACEHOLDER: '-- Rute --',
    DATE_PLACEHOLDER: '-- Pilih Tanggal --',
    EMPTY_ROUTE: '-- Kosong --',
    ACCUMULATION_OPTION: '⚡ Rekap Akumulasi',
    DEFAULT_SELECT_PERIOD: 'Pilih Rute & Periode',
    NO_ROUTE_SHEET_WARNING: (route: string, month: string, year: number) =>
      `⚠️ Belum ada sheet untuk rute ${route} periode ${month} ${year}. Klik + Tambah Rute untuk mendaftarkannya.`,
    DUPLICATE_ROUTE_WARNING: (route: string, month: string, year: number) =>
      `Rute ${route} untuk periode ${month} ${year} sudah terdaftar.`,
    DUPLICATE_SHEET_WARNING: (registeredRoute: string, month: string, year: number) =>
      `Spreadsheet ini sudah terdaftar untuk rute ${registeredRoute} pada periode ${month} ${year}.`,
    ROUTE_INPUT_PLACEHOLDER: 'Kode rute (misal: 115, 76, 78A)',
    ROUTE_INPUT_HINT: 'Ketik nomor / kode trayek (contoh: 115, 76, 78A)',
    YEAR_INPUT_PLACEHOLDER: 'Tahun',
    SHEET_URL_PLACEHOLDER: 'Link Google Sheets...',
    TITLE_NO_ROUTE_DATA: 'Belum ada data rute',
    TITLE_SELECT_YEAR_FIRST: 'Pilih tahun terlebih dahulu',
    TITLE_SELECT_MONTH_FIRST: 'Pilih bulan terlebih dahulu',
    TITLE_SELECT_ROUTE_FIRST: 'Pilih rute terlebih dahulu',
    TITLE_SELECT_MONTH: 'Pilih bulan',
    TITLE_SELECT_ROUTE: 'Pilih rute',
    TITLE_SELECT_DATE: 'Pilih tanggal',
    ADD_ROUTE_LABEL_CODE: 'Kode Trayek Rute',
    ADD_ROUTE_LABEL_MONTH: 'Bulan Sheet',
    ADD_ROUTE_LABEL_YEAR: 'Tahun',
    SHEET_URL_LABEL: 'URL / Link Google Spreadsheet',
    ACTIVE_ROUTE_TITLE: (route: string) => `Kode Rute Aktif: ${route}. Klik untuk memilih rute.`,
    ACTIVE_ROUTE_ARIA: (route: string) => `Rute aktif: ${route}`,
    DEFAULT_PICK_ROUTE: 'Pilih Rute',
  },
  PROFILE_MENU: {
    TITLE: 'Tutup Menu',
    DEFAULT_USER_NAME: 'Petugas Operasional',
    DEFAULT_USER_EMAIL: 'pdo.utara@transjakarta.co.id',
    ADMIN_SECTION: 'ADMINISTRASI SISTEM',
    USER_MANAGEMENT: 'Kelola Pengguna',
    USER_MANAGEMENT_DESC: 'Atur akun, peran (role), & status aktif',
    AUDIT_LOG: 'Log Aktivitas & Audit',
    AUDIT_LOG_DESC: 'Riwayat tindakan dan input operasional',
    COMING_SOON: 'Coming Soon',
    COMING_SOON_TITLE: 'Fitur sedang dalam penyesuaian (Coming Soon)',
    FEATURES_SECTION: 'FITUR & UTILITAS',
    REGIONAL_MONITORING: 'Monitoring Wilayah & Laporan WA',
    REGIONAL_MONITORING_DESC: 'Rekap 18 rute & generator pesan WA',
    CROSS_PERIOD: 'Rekap Akumulasi Lintas Periode',
    FORMAT_SHEET: 'Rapikan & Format Spreadsheet',
    FORMAT_SHEET_DESC: 'Terapkan perataan & warna baris ke Google Sheets',
    THEME_MODE: 'Mode Tampilan',
    DARK_MODE: 'Dark Mode',
    LIGHT_MODE: 'Light Mode',
    OFFLINE_MODE: 'Mode Offline',
    SYNC_QUEUE: 'Antrean Sync',
    PENDING_SUFFIX: 'terpending',
    SESSION_NOTE: '⏱️ Waktu aktif sesi tercatat otomatis untuk pemantauan operasional.',
    LOGOUT_BTN: 'Keluar Akun (Logout)',
    SELECT_ROUTE_DATE_FIRST: 'Pilih rute dan tanggal terlebih dahulu.',
    FORMATTING_PROGRESS: 'Sedang merapikan spreadsheet...',
    FORMAT_SUCCESS: 'Spreadsheet berhasil dirapikan & diformat!',
    FORMAT_FAILED: 'Gagal menerapkan format spreadsheet.',
  },
  UNIT_CARD: {
    ARMADA: 'Unit Bus',
    DRIVER: 'Pramudi',
    KM: 'KM Tempuh',
    TOA: 'TOA',
    MANUAL: 'Manual',
    TOTAL_PAX: 'Pelanggan',
    RITASE_DIFF: 'Selisih Ritase',
    STATUS_OPERASI: 'Status Operasi',
    STATUS_FULL_COMPLETE: 'S1 & S2 Lengkap',
    STATUS_SHIFT_1_ONLY: 'Negatif Data S2',
    STATUS_SHIFT_2_ONLY: 'Negatif Data S1',
    STATUS_INCOMPLETE: 'Parsial',
    STATUS_EMPTY: 'Negatif Data S1 & S2',
    ARIA_VIEW_DETAIL: (unit: string) => `Lihat detail unit ${unit}`,
    KM_UNIT: 'KM',
    PNP_UNIT: 'Pnp',
    RIT_UNIT: 'Rit',
  },
  SYNC_QUEUE_TITLE: 'Buka antrean sinkronisasi',
  REFRESH_OFFLINE_ERR: 'Tidak bisa refresh saat offline',
  MISSING_COLS_WARNING: (cols: string) =>
    `⚠️ Kolom berikut tidak terdeteksi di header sheet dan TIDAK akan tersimpan: ${cols}. Hubungi admin untuk memperbaiki header.`,
  MISSING_COLS_TITLE: 'Beberapa kolom tidak ditemukan di Sheet:',
  QUEUE_SYNC_SUCCESS: 'Data antrean berhasil disinkronkan ke Google Sheets!',
  QUEUE_ITEM_DELETED: 'Item berhasil dihapus dari antrean.',
  SESSION_REFRESH_SUCCESS: 'Sesi berhasil diperbarui!',
  SESSION_REFRESH_FAIL: 'Gagal memperbarui sesi. Silakan coba lagi.',
  SELECT_ROUTE_FIRST: 'Silakan pilih atau paste link Google Sheet terlebih dahulu',
  INVALID_SHEET_LINK: 'Link tidak valid. Pastikan Anda meng-copy link dari Google Sheets.',
  LOAD_DATA_FAIL: 'Gagal memuat data. Periksa kembali link dan tab Anda.',
  QUEUE_RETRYING: 'Mencoba menyinkronkan kembali...',
  QUEUE_USE_SERVER: 'Menggunakan data dari server.',
  QUEUE_OVERWRITE_SERVER: 'Menimpa data server dengan data lokal...',
  ACCUMULATION_LOAD_FAIL: 'Gagal memuat data akumulasi.',
  SHEET_NOT_LOADED: 'Data spreadsheet belum dimuat.',
  TOA_TREND: {
    TITLE: 'Grafik Pelanggan Harian',
    ERROR_MESSAGE: 'Data grafik tren tidak dapat dimuat saat ini. Silakan periksa koneksi internet Anda.',
    PEAK_LABEL: 'Tertinggi',
    LOWEST_LABEL: 'Terendah',
    AVG_LABEL: 'Rata-rata',
    AVG_UNIT: 'Pnp/Hari',
    DATE_PREFIX: 'Tgl ',
    LEGEND_UP: 'Naik',
    LEGEND_SLIGHT_DOWN: 'Turun Sedikit',
    LEGEND_DRASTIC_DOWN: 'Turun Drastis (≥20%)',
  },
  KPIS: {
    TITLE: 'Capaian Pelanggan & Km',
    TOTAL_KM: 'TOTAL KM',
    TOTAL_KM_UNIT: 'KM',
    TOA_PASSENGERS: 'PELANGGAN (TOA)',
    KM_PER_BUS: 'KM/Bus:',
    PASSENGERS_PER_KM: 'Pnp/Km:',
  },
  SHIFT_COMPARISON: {
    TITLE: 'Komparasi Pelanggan',
    SHIFT_1: 'SHIFT 1',
    SHIFT_2: 'SHIFT 2',
    TOA_LABEL: 'TOA:',
    MANUAL_LABEL: 'Manual:',
    TOTAL_LABEL: 'Total:',
  },
  COMPLETION_STATUS: {
    TITLE: 'Unit Dengan Keterangan Tertentu',
    UNIT_COUNT: (count: number) => `${count} Unit`,
    JUMP_TO_UNIT_TITLE: 'Klik untuk lompat ke unit ini',
    NO_NOTES: 'Tidak ada keterangan unit untuk tanggal ini.',
  },
  BUS_LIST: {
    SEARCH_PLACEHOLDER: 'Cari No. Body Unit...',
    FILTER_BTN: 'Filter',
    FILTER_UNFINISHED: 'Sisa Unit',
    EMPTY_SEARCH: (query: string) => `Tidak ada unit yang ditemukan dengan nomor "${query}"`,
    EMPTY_SUMMARY: (query: string) => `Tidak ada armada yang sesuai dengan kata kunci "${query}"`,
    SET_TRIP_BTN: 'Set Jumlah Trip',
    SET_TRIP_TITLE: 'Set Jumlah Trip Armada',
    SET_TRIP_WITH_COUNT: (p: string, q: string) => `Set Jumlah Trip: Pergi ${p} · Pulang ${q}`,
    SET_TRIP_SUCCESS: (p: string, q: string, count: number) =>
      `Trip Operasional (${p}/${q}) berhasil disimpan ke Spreadsheet untuk ${count} unit!`,
    SET_TRIP_FAILED: 'Gagal Menyimpan Set Jumlah Trip',
    COPY_KM_SUCCESS: (count: number, noteSuffix: string) =>
      `KM Akhir S1 berhasil disalin ke KM Awal S2 untuk ${count} unit bus${noteSuffix}!`,
    COPY_KM_FAILED: 'Gagal Menyalin KM Massal',
    COPY_KM_SKIPPED_ALL: (count: number) =>
      `Seluruh unit yang memiliki KM Akhir S1 (${count} unit) memiliki catatan keterangan, sehingga proses salin dilewati.`,
    COPY_KM_NO_DATA: 'Tidak ada unit bus yang memiliki data KM Akhir Shift 1.',
    COPY_KM_READY_COUNT: (count: number) => `${count} unit`,
    COPY_KM_READY_TEXT: 'siap disalin',
    COPY_KM_SKIPPED_TEXT: (count: number) => `(${count} berketerangan dilewati)`,
    COPY_KM_BTN: '📋 Salin Semua KM S1',
    ACCUMULATION_LOCKED: 'Penginputan dikunci pada mode Rekap Akumulasi.',
    SAVE_ERROR_GENERIC: 'Terjadi kesalahan saat menyimpan data ke spreadsheet.',
    COPY_KM_ALL_FILLED: 'Semua unit bus sudah memiliki nilai KM Awal Shift 2.',
    ALL_UNITS_FILLED: '🎉 Semua unit pada filter ini telah selesai diisi!',
    CATEGORIES: {
      ALL: 'Semua Kolom',
      TRIP: 'Trip Armada',
      TOA_S1: 'TOA S1',
      TOTAL_TOA: 'Total TOA',
      KM_AWAL_1: 'KM Awal S1',
      KM_AKHIR_1: 'KM Akhir S1',
      KM_AWAL_2: 'KM Awal S2',
      KM_AKHIR_2: 'KM Akhir S2',
      NOTES: 'Catatan / Keterangan',
    },
  },
  BUS_CARD_ACTIONS: {
    SGO_CONFIRM_TITLE: 'Konfirmasi Operasional Bus',
    SGO_CONFIRM_HTML: (unit: string, ket: string) =>
      `Unit <strong>${unit}</strong> saat ini berstatus <strong>${ket}</strong>.<br><br>Apakah unit ini dioperasikan (SGO)?`,
    SGO_CONFIRM_BTN: 'Jadikan SGO & Buka Form',
    SGO_CANCEL_INPUT_BTN: 'Tetap Lanjut Input',
    SGO_DENY_BTN: 'Batal',
    RITASE_DEFICIT_TOOLTIP: (p: string | number, q: string | number, tp: number, tq: number) =>
      `Kurang Ritase: ${p}/${q} Rit (Target Rute: ${tp}/${tq} Rit). Klik untuk edit Trip.`,
    FULL_TARGET_TOOLTIP: (p: string | number, q: string | number, tp: number, tq: number) =>
      `Target Ritase Tercapai Penuh: ${p}/${q} Rit (Target: ${tp}/${tq} Rit). Klik untuk edit Trip.`,
    RITASE_TARGET_TOOLTIP: (tp: number, tq: number) =>
      `Target Rute: ${tp}/${tq} Rit. Klik untuk edit Trip.`,
    DEFAULT_TRIP_TITLE: 'Trip Operasional (Klik untuk edit Trip per unit)',
    TRIP_BADGE_DEFICIT: (p: string | number, q: string | number) => `⚠️ ${p}/${q} Rit (Kurang)`,
    TRIP_BADGE_ACHIEVED: (p: string | number, q: string | number) => `${p}/${q} Rit (Tercapai)`,
    TRIP_BADGE_NORMAL: (p: string | number, q: string | number) => `${p}/${q} Rit`,
    RITASE_DEFICIT_CARD: (p: string | number, q: string | number, tp: number, tq: number) =>
      `Kurang Ritase: ${p}/${q} Rit (Target Rute: ${tp}/${tq} Rit)`,
    RITASE_IMBALANCED_CARD: (p: string | number, q: string | number) =>
      `Trip Tidak Seimbang: ${p}/${q} Rit`,
    RITASE_TARGET_CARD: (p: string | number, q: string | number) =>
      `Target Tercapai: ${p}/${q} Rit`,
    SAVED_TO_OFFLINE_QUEUE: (unit: string) =>
      `Unit ${unit} disimpan ke antrean offline`,
    SAVE_FAILED: 'Gagal menyimpan data bus ke Google Sheets.',
    WAITING_SIGNAL: 'Menunggu Sinyal',
    EMPTY_BADGE: 'Kosong',
    KM_UNIT: 'KM',
    PNP_UNIT: 'Pnp',
  },
  ACCUMULATION_SHEET: {
    TITLE: 'Rekap Akumulasi Lintas Periode',
    DESC: 'Pilih tanggal, bulan, dan tahun awal s/d tanggal, bulan, dan tahun akhir dari data yang tersedia.',
    FROM_LABEL: 'DARI PERIODE',
    TO_LABEL: 'SAMPAI PERIODE',
    APPLY_BTN: 'Terapkan Akumulasi Lintas Periode',
    RESET_BTN: 'Kembali ke Mode Harian (Matikan Akumulasi)',
    LOADING: 'Memuat akumulasi data...',
    ERROR_DATE_RANGE: "Periode 'Dari' harus lebih awal atau sama dengan periode 'Sampai'.",
    ERROR_SAME_MONTH_DATE: "Tanggal 'Dari' harus lebih awal atau sama dengan tanggal 'Sampai'.",
  },
} as const;

