/**
 * Kamus teks antarmuka: Dashboard Monitoring Wilayah 18 Rute untuk Korlap / Pimpinan.
 */
export const TEXT_MONITORING = {
  HEADER: {
    TITLE: 'Monitoring Wilayah Utara',
    SUBTITLE: 'Dashboard All Route & Rekapitulasi Harian Transjakarta',
    BTN_BACK: 'Operasi Rute',
    BTN_BACK_TITLE: 'Kembali ke Operasi Rute Tunggal',
    BTN_WA_REPORT: 'Buat Laporan WA',
    BTN_SYNC_GLOBAL: 'Tarik Data Global',
    BTN_SYNC_GLOBAL_TITLE: 'Tarik Data 18 Rute dari Spreadsheet Capaian Global Wilayah',
    REFRESH_TITLE: 'Perbarui Data',
  },
  SYNC_MODAL: {
    TITLE: 'Tarik Data Spreadsheet Global',
    DESC: 'Tarik otomatis metrik capaian (TOA, Manual, KM, Ritase) 18 rute dari spreadsheet global wilayah ke database.',
    LABEL_URL: 'Link Spreadsheet Global Wilayah',
    PLACEHOLDER_URL: 'https://docs.google.com/spreadsheets/d/...',
    LABEL_SHEET_NAME: 'Nama Lembar (Bulan)',
    PLACEHOLDER_SHEET_NAME: 'Contoh: SEPTEMBER 2026',
    BTN_CONFIRM: 'Mulai Sinkronisasi',
    BTN_CANCEL: 'Batal',
    SYNCING: 'Sedang membaca dan menyinkronkan 18 rute...',
    SUCCESS_TITLE: 'Sinkronisasi Berhasil',
    SUCCESS_DESC: (count: number) => `Berhasil menyinkronkan ${count} rute ke database.`,
    FAILED_TITLE: 'Sinkronisasi Gagal',
  },
  ERROR_STATE: {
    TITLE: 'Gagal Memuat Data',
    RETRY_BTN: 'Coba Lagi',
  },
  READINESS: {
    LABEL: 'Status Kelengkapan Laporan PDO Wilayah:',
    SUMMARY: (submitted: number, total: number, pct: number) =>
      `${submitted} / ${total} Rute Siap (${pct}%)`,
    SUMMARY_DETAILED: (filled: number, total: number, app: number, sheet: number) =>
      `${filled}/${total} Rute Terisi • ${app} Input App • ${sheet} Tarik Sheet`,
    LEGEND_VERIFIED: 'Terverifikasi:',
    LEGEND_SUBMITTED: 'Submitted:',
    LEGEND_DRAFT: 'Draft:',
    LEGEND_EMPTY: 'Belum Diisi:',
  },
  KPI: {
    FLEET_LABEL: 'Armada Wilayah',
    FLEET_UNIT: 'bus',
    FLEET_PCT: (pct: string) => `${pct}% Armada`,
    FLEET_BREAKDOWN: (s1: number, s2: number) => `S1: ${s1} | S2: ${s2}`,
    PASSENGER_LABEL: 'Total Pelanggan',
    PASSENGER_UNIT: 'org',
    PASSENGER_BREAKDOWN: (s1: string, s2: string) => `S1: ${s1} S2: ${s2}`,
    KM_LABEL: 'Total Jarak Tempuh',
    KM_UNIT: 'km',
    KM_AVG: (avg: string) => `Rerata / Bus: ${avg} km`,
    KM_AVG_LABEL: 'Rerata / Bus:',
    KM_ACHIEVE: (pct: string) => `Cap: ${pct}%`,
    SHIFT_DISTRIBUTION: 'Distribusi Shift',
    SHIFT_1_ROW: 'Shift 1:',
    SHIFT_2_ROW: 'Shift 2:',
  },
  TABS: {
    ALL_ROUTES: (count: number) => `Semua Rute (${count})`,
    ALL_LABEL: 'Semua Rute',
  },
  ROUTE_CARD: {
    OPEN_ROUTE_TITLE: 'Buka rute ini',
    HEADWAY_LABEL: (min: number, max: number) => `Headway: ${min} - ${max} mnt`,
    KORLAP_PREFIX: 'Korlap:',
    METRIC_ARMADA: 'Armada',
    METRIC_PASSENGERS: 'Pelanggan',
    METRIC_KM: 'KM Tempuh',
    KM_PER_BUS_PREFIX: 'KM/B:',
    JAM_PREFIX: 'Macet:',
    ISSUE_PREFIX: 'Kendala:',
    BTN_VERIFY: 'Verifikasi',
    BADGE_VERIFIED: 'Verified',
    BADGE_SUBMITTED: 'Submitted',
    BADGE_DRAFT: 'Draft',
    BADGE_EMPTY: 'Belum Diisi',
  },
  NAV: {
    DASHBOARD: 'Dashboard',
    ROUTES: 'Rute',
    FLEET_STATUS: 'Status Armada',
    WA_REPORT: 'Laporan WA',
    PROFILE: 'Profil',
  },
  BULK_VERIFY: {
    BUTTON_LABEL: (count: number) => `Verifikasi Semua (${count})`,
    CONFIRM_TITLE: 'Verifikasi Massal Laporan',
    CONFIRM_TEXT: (count: number) =>
      `Apakah Anda yakin ingin memverifikasi ${count} rute yang telah disubmit sekaligus?`,
    CONFIRM_BUTTON: 'Ya, Verifikasi Semua',
    CANCEL_BUTTON: 'Batal',
    SUCCESS_TOAST: (count: number) =>
      `Berhasil memverifikasi ${count} rute sekaligus!`,
    NO_ROUTES_TO_VERIFY: 'Tidak ada rute berstatus submitted yang siap diverifikasi.',
  },
  DASHBOARD: {
    PROGRESS_TITLE: 'Kesiapan Status Armada PDO',
    PROGRESS_RATIO: (confirmed: number, total: number) =>
      `${confirmed} / ${total} Rute Terkonfirmasi`,
    PROGRESS_ALL_CONFIRMED: 'Seluruh rute telah mengonfirmasi status armada.',
    CHART_TITLE: 'Tren TOA Penumpang per Rute',
    CHART_SUBTITLE: 'Perbandingan total pelanggan 18 rute hari ini',
    CHART_TOOLTIP_SHIFT: (s1: number, s2: number) =>
      `TOA Shift 1: ${s1.toLocaleString('id-ID')} • Shift 2: ${s2.toLocaleString('id-ID')}`,
    CHART_TOA_UNIT: 'TOA',
    CHART_TARGET_PCT: (pct: string) => `${pct}% dari Target`,
    CHART_TARGET_ZERO: 'Target 0',
    CHART_BAR_TITLE: (route: string, val: string) => `${route}: ${val} TOA`,
    MACRO_KPIS: {
      PASSENGERS: 'Total Pelanggan',
      TRIPS: 'Total Ritase',
      DISTANCE: 'Total Jarak Tempuh',
      PRODUCTIVITY: 'Produktivitas',
      TARGET_PCT: (pct: string) => `Capaian Target: ${pct}%`,
      PER_BUS: 'per Bus',
      PER_KM: 'per KM',
    },
    SHIFT_SPLIT: {
      TITLE: 'Perbandingan Beban Operasional Shift',
      SHIFT_1: 'Shift 1 (Pagi)',
      SHIFT_2: 'Shift 2 (Siang)',
      DETAIL_PASSENGERS: (toa: number, manual: number) =>
        `TOA: ${toa.toLocaleString('id-ID')} | Manual: ${manual.toLocaleString('id-ID')}`,
    },
    LEADERBOARD: {
      TITLE: 'Kinerja Rute Wilayah',
      TOP_3: '3 Rute Tertinggi',
      BOTTOM_3: '3 Rute Butuh Perhatian',
      PASSENGERS_COUNT: (count: number) => `${count.toLocaleString('id-ID')} Pelanggan`,
      TARGET_PCT_BADGE: (pct: string) => `${pct}% Target`,
    },
  },
  FLEET_TAB: {
    TITLE: 'Status Armada Wilayah (Non-SGO)',
    TOTAL_FLEET: 'Total Armada',
    SGO_LABEL: 'Siap Guna (SGO)',
    NON_SGO_LABEL: 'Kendala (Non-SGO)',
    ALL_SHIFTS: 'Semua Shift',
    ALL_NON_SGO: 'Semua Kendala',
    EMPTY_TITLE: 'Seluruh Armada Beroperasi Normal',
    EMPTY_DESC: 'Luar biasa! Seluruh armada 18 rute berstatus SGO (Siap Guna Operasi) tanpa kendala.',
    ROUTE_ISSUES_COUNT: (count: number) => `${count} Bus Kendala`,
    NOTES_PREFIX: 'Kendala:',
    SHIFT_PREFIX: 'Shift:',
  },
  INGESTION: {
    BUTTON_LABEL: 'Load All',
    BUTTON_LOADING: 'Loading...',
    TOOLTIP: 'Tarik otomatis data 18 sheet rute individu ke database',
    MODAL_TITLE: 'Sinkronisasi 18 Rute (Load All)',
    MODAL_SUBTITLE: 'Menarik ringkasan capaian langsung dari Google Sheets rute',
    PROGRESS_INIT: 'Menghubungi konfigurasi spreadsheet rute...',
    PROGRESS_FETCHING: (route: string, current: number, total: number) =>
      `Menarik rute ${route} (${current} dari ${total})...`,
    PROGRESS_SAVING: (route: string) => `Menyimpan rekapitulasi ${route}...`,
    PROGRESS_COMPLETE: 'Seluruh rute berhasil disinkronkan!',
    PROGRESS_PROCESSED_LABEL: 'Rute Terproses',
    PROGRESS_SKIPPED_LABEL: 'Dilewati (Input App)',
    SUCCESS_TOAST: (appCount: number, sheetCount: number) =>
      `Berhasil menyinkronkan: ${appCount} rute dari App, ${sheetCount} rute dari Sheet.`,
    PARTIAL_WARN: (errorCount: number) =>
      `Sinkronisasi selesai dengan ${errorCount} rute terkendala.`,
    FAILED_TITLE: 'Gagal Menarik Data Rute',
  },
  PROVENANCE: {
    APP_INPUT: 'Input App',
    SHEET_SYNC: 'Tarik Sheet',
    EMPTY: 'Belum Ada Data',
  },
} as const;
