/**
 * Kamus teks antarmuka: Autentikasi, login Google, status izin akun, dan sesi.
 */
export const TEXT_AUTH = {
  TITLE: 'PUSM - Masuk Akun',
  SUBTITLE: 'Aplikasi Operasional PDO Wilayah Utara Transjakarta',
  DESCRIPTION: 'Silakan masuk menggunakan akun Google resmi Transjakarta yang terdaftar.',
  BADGE: 'Operasional Mikrotrans Transjakarta',
  HERO_DESC: 'Aplikasi pencatatan dan pemantauan tugas operasional harian armada Transjakarta Mikrotrans Wilayah Utara yang terhubung langsung ke Google Spreadsheet internal.',
  SIGN_IN_BTN: 'Masuk dengan Akun Google',
  ACCOUNT_HINT: 'Gunakan akun Google yang sudah didaftarkan oleh admin atau pengawas.',
  SIGN_IN_LOADING: 'Menghubungkan ke Google...',
  SIGN_OUT_BTN: 'Keluar Akun',
  LOGOUT_LABEL: 'Keluar Akun (Logout)',
  VERIFYING_ACCOUNT: 'Memverifikasi izin akun...',
  NOT_ALLOWED: 'Akun Anda belum terdaftar. Silakan hubungi admin atau pengawas untuk pendaftaran akses.',
  UNVERIFIED_IDENTITY: 'Tidak dapat memverifikasi identitas akun Google Anda. Silakan coba masuk kembali.',
  SESSION_EXPIRED_TITLE: 'Sesi Berakhir',
  SESSION_EXPIRED_MSG: 'Sesi Google Sheets Anda telah kedaluwarsa. Silakan login ulang untuk melanjutkan.',
  SESSION_EXPIRED_BANNER: 'Sesi Google Sheets kedaluwarsa. Ketuk tombol untuk perbarui sesi.',
  SESSION_NEED_REAUTH: 'Sesi Google perlu diperbarui untuk sinkronisasi data.',
  REAUTH_BTN: 'Login Ulang',
  REFRESH_SESSION_BTN: 'Perbarui Sesi',
  INIT_ERROR_TITLE: 'Gagal Inisialisasi Layanan',
  INIT_ERROR_FALLBACK: 'Gagal menginisialisasi layanan Google API.',
  ABOUT_TITLE: 'Tentang PUSM',
  VS_TITLE: 'Spreadsheet vs PUSM',
  PERMISSIONS_TITLE: 'PUSM Perlu Izin Akun Google',
  FEATURES_TITLE: 'Fitur Utama Aplikasi',
  LEGAL: {
    PRIVACY: 'Kebijakan Privasi',
    TERMS: 'Syarat & Ketentuan',
    DEVELOPER: 'Kontak Pengembang',
    COPYRIGHT: '© 2026 PUSM — PDO Utara Spreadsheet Mobile. Hak cipta dilindungi.',
  },
  FEATURE_CARDS: {
    CARD_1_TITLE: 'Dashboard Capaian Rute',
    CARD_1_DESC: 'Rekap capaian ritase, kilometer, dan pelanggan per armada secara real-time.',
    CARD_2_TITLE: 'Pencarian Unit & Catatan',
    CARD_2_DESC: 'Cari nomor bodi unit cepat, catat kondisi siap jalan atau kendala lapangan.',
    CARD_3_TITLE: 'Form Cepat & Presisi',
    CARD_3_DESC: 'Input data terarah yang langsung tersimpan rapi ke spreadsheet resmi pengawas.',
  },
} as const;

