/**
 * Kamus teks antarmuka: Header PUSM, selektor rute, tab navigasi bawah, kartu unit bus, dan menu profil.
 */
export const TEXT_DASHBOARD = {
  APP_TITLE: 'PUSM',
  APP_SUBTITLE: 'PDO Utara Spreadsheet Mobile',
  NAV_MAIN: 'Navigasi Utama',
  TABS: {
    INPUT_SS: 'Input SS',
    INPUT_SHORT: 'Input',
    DASHBOARD: 'Dashboard',
    DASHBOARD_SHORT: 'Ringkasan',
    UNIT_LIST: 'Daftar Unit',
    UNIT_SHORT: 'Armada',
    ACCUMULATION: 'Akumulasi',
    MORE: 'Lainnya',
    MORE_SHORT: 'Menu',
  },
  SWITCHER: {
    REGIONAL_MONITORING: 'Wilayah',
    TITLE: 'Buka Dashboard Monitoring Wilayah & Laporan WA',
  },
  ROUTE_SELECTOR: {
    LABEL: 'Rute & Tanggal Operasional',
    TITLE: 'Pilih Rute & Tanggal',
    ROUTE_PERIOD_LABEL: 'Pilih Rute & Periode',
    SEARCH_PLACEHOLDER: 'Cari kode rute...',
    SELECT_ROUTE_PROMPT: 'Pilih Rute',
    NO_ROUTES_FOUND: 'Rute tidak ditemukan',
    ACCUMULATION_RANGE_LABEL: 'Rentang Akumulasi Tanggal',
    EXIT_ACCUMULATION: 'Kembali ke Harian',
    EXIT_ACCUMULATION_BTN: 'Kembali ke Harian ✕',
    ACCUMULATION_ACTIVE_BANNER: 'Mode Rekap Akumulasi Aktif',
    LOAD_DATA_BTN: 'Load Data Unit',
    SAVING_ROUTE: 'Menyimpan...',
    SAVE_ROUTE_BTN: 'Simpan Rute',
    ADD_ROUTE_BTN: 'Tambah Rute',
    ADD_NEW_ROUTE: 'Tambah Rute Baru',
    CHECKING_ACCESS: 'Memeriksa akses Google Sheets...',
    CONNECTED_READY: 'Spreadsheet terhubung & siap digunakan',
    CANNOT_ACCESS: 'Tidak dapat mengakses spreadsheet.',
    ROUTE_CODE_REQUIRED: 'Nomor / kode rute wajib diisi (misal: 115, 76, 78A).',
    YEAR_INVALID: 'Tahun tidak valid. Isi tahun antara 2020 - 2099.',
    SAVE_ROUTE_FAILED: 'Gagal menyimpan rute.',
    CLICK_TO_EXPAND: 'Klik untuk membuka Form Pemilihan',
    CLICK_TO_COLLAPSE: 'Klik header ini untuk menciutkan form',
    YEAR_LABEL: 'Tahun',
    MONTH_LABEL: 'Bulan',
    ROUTE_LABEL: 'Rute',
    DATE_LABEL: 'Tanggal',
    YEAR_PLACEHOLDER: '-- Tahun --',
    MONTH_PLACEHOLDER: '-- Bulan --',
    ROUTE_PLACEHOLDER: '-- Rute --',
    DATE_PLACEHOLDER: '-- Pilih Tanggal --',
    EMPTY_ROUTE: '-- Kosong --',
    ACCUMULATION_OPTION: '⚡ Rekap Akumulasi',
    DEFAULT_SELECT_PERIOD: 'Pilih Rute & Periode',
    NO_ROUTE_SHEET_WARNING: (route: string, month: string, year: number) =>
      `⚠️ Belum ada sheet untuk rute ${route} periode ${month} ${year}. Klik + Tambah Rute untuk mendaftarkannya.`,
    DUPLICATE_ROUTE_WARNING: (route: string, month: string, year: number) =>
      `Rute ${route} untuk periode ${month} ${year} sudah terdaftar.`,
    DUPLICATE_SHEET_WARNING: (registeredRoute: string, month: string, year: number) =>
      `Spreadsheet ini sudah terdaftar untuk rute ${registeredRoute} pada periode ${month} ${year}.`,
    ROUTE_INPUT_PLACEHOLDER: 'Kode rute (misal: 115, 76, 78A)',
    ROUTE_INPUT_HINT: 'Ketik nomor / kode trayek (contoh: 115, 76, 78A)',
    YEAR_INPUT_PLACEHOLDER: 'Tahun',
    SHEET_URL_PLACEHOLDER: 'Link Google Sheets...',
  },
  PROFILE_MENU: {
    TITLE: 'Tutup Menu',
    DEFAULT_USER_NAME: 'Petugas Operasional',
    DEFAULT_USER_EMAIL: 'pdo.utara@transjakarta.co.id',
    ADMIN_SECTION: 'ADMINISTRASI SISTEM',
    USER_MANAGEMENT: 'Kelola Pengguna',
    USER_MANAGEMENT_DESC: 'Atur akun, peran (role), & status aktif',
    AUDIT_LOG: 'Log Aktivitas & Audit',
    AUDIT_LOG_DESC: 'Riwayat tindakan dan input operasional',
    COMING_SOON: 'Coming Soon',
    COMING_SOON_TITLE: 'Fitur sedang dalam penyesuaian (Coming Soon)',
    FEATURES_SECTION: 'FITUR & UTILITAS',
    REGIONAL_MONITORING: 'Monitoring Wilayah & Laporan WA',
    REGIONAL_MONITORING_DESC: 'Rekap 18 rute & generator pesan WA',
    CROSS_PERIOD: 'Rekap Akumulasi Lintas Periode',
    FORMAT_SHEET: 'Rapikan & Format Spreadsheet',
    FORMAT_SHEET_DESC: 'Terapkan perataan & warna baris ke Google Sheets',
    THEME_MODE: 'Mode Tampilan',
    DARK_MODE: 'Dark Mode',
    LIGHT_MODE: 'Light Mode',
    OFFLINE_MODE: 'Mode Offline',
    SYNC_QUEUE: 'Antrean Sync',
    PENDING_SUFFIX: 'terpending',
    SESSION_NOTE: '⏱️ Waktu aktif sesi tercatat otomatis untuk pemantauan operasional.',
    LOGOUT_BTN: 'Keluar Akun (Logout)',
    SELECT_ROUTE_DATE_FIRST: 'Pilih rute dan tanggal terlebih dahulu.',
    FORMATTING_PROGRESS: 'Sedang merapikan spreadsheet...',
    FORMAT_SUCCESS: 'Spreadsheet berhasil dirapikan & diformat!',
    FORMAT_FAILED: 'Gagal menerapkan format spreadsheet.',
  },
  UNIT_CARD: {
    ARMADA: 'Unit Bus',
    DRIVER: 'Pramudi',
    KM: 'KM Tempuh',
    TOA: 'TOA',
    MANUAL: 'Manual',
    TOTAL_PAX: 'Pelanggan',
    RITASE_DIFF: 'Selisih Ritase',
    STATUS_OPERASI: 'Status Operasi',
  },
  SYNC_QUEUE_TITLE: 'Buka antrean sinkronisasi',
  REFRESH_OFFLINE_ERR: 'Tidak bisa refresh saat offline',
  MISSING_COLS_WARNING: (cols: string) =>
    `⚠️ Kolom berikut tidak terdeteksi di header sheet dan TIDAK akan tersimpan: ${cols}. Hubungi admin untuk memperbaiki header.`,
  MISSING_COLS_TITLE: 'Beberapa kolom tidak ditemukan di Sheet:',
  QUEUE_SYNC_SUCCESS: 'Data antrean berhasil disinkronkan ke Google Sheets!',
  QUEUE_ITEM_DELETED: 'Item berhasil dihapus dari antrean.',
  SESSION_REFRESH_SUCCESS: 'Sesi berhasil diperbarui!',
  SESSION_REFRESH_FAIL: 'Gagal memperbarui sesi. Silakan coba lagi.',
  SELECT_ROUTE_FIRST: 'Silakan pilih atau paste link Google Sheet terlebih dahulu',
  INVALID_SHEET_LINK: 'Link tidak valid. Pastikan Anda meng-copy link dari Google Sheets.',
  LOAD_DATA_FAIL: 'Gagal memuat data. Periksa kembali link dan tab Anda.',
  QUEUE_RETRYING: 'Mencoba menyinkronkan kembali...',
  QUEUE_USE_SERVER: 'Menggunakan data dari server.',
  QUEUE_OVERWRITE_SERVER: 'Menimpa data server dengan data lokal...',
  ACCUMULATION_LOAD_FAIL: 'Gagal memuat data akumulasi.',
  SHEET_NOT_LOADED: 'Data spreadsheet belum dimuat.',
} as const;

