/**
 * Kamus teks antarmuka: Manajemen Pengguna, hak akses RBAC, status akun, dan modal tambah/ubah peran.
 */
export const TEXT_USER_MANAGEMENT = {
  HEADER: {
    TITLE: 'Manajemen Pengguna',
    SUBTITLE: (active: number, total: number) => `${active} aktif dari total ${total} terdaftar`,
    BACK_BTN: 'Kembali',
    BACK_TITLE: 'Kembali ke Dashboard',
    REFRESH_TITLE: 'Muat Ulang Daftar User',
    ADD_BTN: 'Tambah',
  },
  TABS: {
    ALL: 'Semua',
    SUPERADMIN: 'Superadmin',
    ADMIN: 'Admin',
    PETUGAS: 'Petugas',
    INACTIVE: 'Nonaktif',
  },
  SEARCH_PLACEHOLDER: 'Cari berdasarkan nama, email, atau catatan...',
  EMPTY_STATE: {
    TITLE: 'Tidak ada pengguna ditemukan',
    SEARCH_NO_MATCH: 'Tidak ada akun yang cocok dengan kata kunci pencarian.',
    CATEGORY_EMPTY: 'Belum ada pengguna pada kategori ini.',
  },
  CARD: {
    NO_NAME: 'Tanpa Nama',
    YOU_BADGE: 'Anda',
    NEVER_LOGGED_IN: 'Belum pernah login',
    CREATED_BY: (name: string) => `Oleh: ${name}`,
    CREATED_BY_TITLE: (email: string) => `Didaftarkan oleh: ${email}`,
  },
  ROLES: {
    SUPERADMIN_OPTION: 'Superadmin (Kuasa Penuh)',
    ADMIN_OPTION: 'Admin (Kelola Petugas & Rute)',
    PETUGAS_OPTION: 'Petugas Operasional (Input Data Saja)',
  },
  MODAL_ADD: {
    TITLE: 'Tambah Pengguna Baru',
    EMAIL_LABEL: 'Email Akun Google',
    EMAIL_PLACEHOLDER: 'contoh@gmail.com',
    NAME_LABEL: 'Nama Lengkap',
    NAME_PLACEHOLDER: 'Nama Petugas / Pengawas',
    ROLE_LABEL: 'Peran / Hak Akses',
    NOTES_LABEL: 'Catatan Tugas (Opsional)',
    NOTES_PLACEHOLDER: 'Misal: Koridor 1 Shift Pagi',
    CONFIRM_BTN: 'Simpan & Beri Akses',
    CANCEL_BTN: 'Batal',
  },
  MODAL_EDIT_ROLE: {
    TITLE: 'Ubah Peran Pengguna',
    PROMPT: (email: string) => `Pilih peran baru untuk <strong style="color:var(--text-primary)">${email}</strong>:`,
    CONFIRM_BTN: 'Simpan Perubahan',
    CANCEL_BTN: 'Batal',
    BTN_EDIT: 'Ubah Peran',
    BTN_TITLE: 'Ubah Peran / Role',
  },
  MODAL_STATUS: {
    TITLE: 'Konfirmasi Status Akun',
    PROMPT: (actionText: string, email: string) =>
      `<p style="margin:0;font-size:13.5px;color:var(--text-secondary);line-height:1.5;">Apakah Anda yakin ingin <strong>${actionText}</strong> akses login untuk <strong style="color:var(--text-primary)">${email}</strong>?</p>`,
    CONFIRM_ACTIVATE: 'Ya, Aktifkan',
    CONFIRM_DEACTIVATE: 'Ya, Nonaktifkan',
    ACTION_ACTIVATE: 'mengaktifkan',
    ACTION_DEACTIVATE: 'menonaktifkan',
    CANCEL_BTN: 'Batal',
    TITLE_SELF: 'Tidak bisa menonaktifkan akun sendiri',
    TITLE_DEACTIVATE: 'Klik untuk menonaktifkan status akun',
    TITLE_ACTIVATE: 'Klik untuk mengaktifkan status akun',
    LABEL_ACTIVE: 'Aktif',
    LABEL_INACTIVE: 'Nonaktif',
  },
  ALERTS: {
    ACCESS_RESTRICTED: 'Akses Terbatas',
    ADD_USER_FORBIDDEN: 'Hanya Admin atau Superadmin yang berwenang menambahkan pengguna.',
    EDIT_ROLE_FORBIDDEN: 'Hanya Superadmin yang berwenang mengubah peran akun.',
    TOGGLE_STATUS_FORBIDDEN: 'Hanya Admin atau Superadmin yang berwenang mengubah status akun.',
    ADMIN_EDIT_ADMIN_FORBIDDEN: 'Admin tidak dapat mengubah status akun Admin atau Superadmin.',
    ACTION_DENIED: 'Aksi Ditolak',
    CANNOT_DEACTIVATE_SELF: 'Anda tidak dapat menonaktifkan akun Anda sendiri.',
    LOAD_FAILED_TITLE: 'Gagal Memuat Data',
    LOAD_FAILED_TEXT: 'Tidak dapat memuat daftar pengguna dari server.',
    ADD_FAILED_TITLE: 'Gagal Menambah Pengguna',
    EDIT_ROLE_FAILED_TITLE: 'Gagal Mengubah Peran',
    GENERIC_FAILED_TITLE: 'Gagal',
    GENERIC_ERROR: 'Terjadi kesalahan sistem.',
  },
  TOAST: {
    ADD_SUCCESS: (email: string) => `Pengguna ${email} berhasil ditambahkan!`,
    EDIT_ROLE_SUCCESS: (email: string, role: string) => `Peran ${email} diubah menjadi ${role}.`,
    STATUS_SUCCESS: (email: string, statusText: string) => `Akun ${email} berhasil di${statusText}.`,
  },
} as const;
