-- ==============================================================================
-- Script Pemeliharaan: Reset & Renumber Urutan ID Tabel Supabase (SS_PDO)
-- Tanggal: 2026-09-11
-- Tujuan:
-- Mereset seluruh nilai kolom 'id' pada tabel-tabel publik agar kembali berurutan
-- mulai dari 1 sampai N secara presisi, sekaligus menyinkronkan sequence auto-increment
-- (setval) PostgreSQL dan menjaga integritas Foreign Key (ON UPDATE CASCADE).
--
-- Pengecualian:
-- - Tabel 'daily_unit_summaries' (ID unit harian dikecualikan, namun foreign key
--   route_sheet_id tetap diselaraskan secara otomatis agar data tidak korup).
-- - Tabel 'activity_logs' (ID log audit dikecualikan).
--
-- Cara Menjalankan:
-- Copy seluruh isi script ini dan jalankan di Supabase Dashboard -> SQL Editor.
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------------
-- 1. Pastikan seluruh Foreign Key constraint berstatus ON UPDATE CASCADE
--    agar saat ID tabel induk berubah, tabel anak otomatis ikut tersinkronisasi.
-- ------------------------------------------------------------------------------
ALTER TABLE public.route_sheets
  DROP CONSTRAINT IF EXISTS route_sheets_route_id_fkey,
  ADD CONSTRAINT route_sheets_route_id_fkey 
    FOREIGN KEY (route_id) REFERENCES public.routes(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.daily_route_reports
  DROP CONSTRAINT IF EXISTS daily_route_reports_route_id_fkey,
  ADD CONSTRAINT daily_route_reports_route_id_fkey 
    FOREIGN KEY (route_id) REFERENCES public.routes(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.route_operators
  DROP CONSTRAINT IF EXISTS route_operators_route_id_fkey,
  ADD CONSTRAINT route_operators_route_id_fkey 
    FOREIGN KEY (route_id) REFERENCES public.routes(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.daily_unit_summaries
  DROP CONSTRAINT IF EXISTS daily_unit_summaries_route_sheet_id_fkey,
  ADD CONSTRAINT daily_unit_summaries_route_sheet_id_fkey 
    FOREIGN KEY (route_sheet_id) REFERENCES public.route_sheets(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- ------------------------------------------------------------------------------
-- 2. Ubah kolom identity menjadi GENERATED BY DEFAULT agar nilai id dapat di-update
-- ------------------------------------------------------------------------------
ALTER TABLE public.routes ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.route_sheets ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.user_profiles ALTER COLUMN id SET GENERATED BY DEFAULT;

-- ------------------------------------------------------------------------------
-- 3. Renumbering Tabel 'routes' (1 .. N)
-- ------------------------------------------------------------------------------
UPDATE public.routes SET id = id + 100000;

WITH renumbered_routes AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY route_code) AS new_id
  FROM public.routes
)
UPDATE public.routes r
SET id = rr.new_id
FROM renumbered_routes rr
WHERE r.id = rr.id;

-- ------------------------------------------------------------------------------
-- 4. Renumbering Tabel 'route_sheets' (1 .. N)
-- ------------------------------------------------------------------------------
UPDATE public.route_sheets SET id = id + 100000;

WITH renumbered_sheets AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY route_id, year, month) AS new_id
  FROM public.route_sheets
)
UPDATE public.route_sheets s
SET id = rs.new_id
FROM renumbered_sheets rs
WHERE s.id = rs.id;

-- ------------------------------------------------------------------------------
-- 5. Renumbering Tabel 'user_profiles' (1 .. N)
-- ------------------------------------------------------------------------------
UPDATE public.user_profiles SET id = id + 100000;

WITH renumbered_users AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS new_id
  FROM public.user_profiles
)
UPDATE public.user_profiles u
SET id = ru.new_id
FROM renumbered_users ru
WHERE u.id = ru.id;

-- ------------------------------------------------------------------------------
-- 6. Renumbering Tabel 'route_operators' (1 .. N)
-- ------------------------------------------------------------------------------
UPDATE public.route_operators SET id = id + 100000;

WITH renumbered_ro AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY route_id, operator_id) AS new_id
  FROM public.route_operators
)
UPDATE public.route_operators ro
SET id = rro.new_id
FROM renumbered_ro rro
WHERE ro.id = rro.id;

-- ------------------------------------------------------------------------------
-- 7. Renumbering Tabel 'operators' (1 .. N jika ada gap)
-- ------------------------------------------------------------------------------
UPDATE public.operators SET id = id + 100000;

WITH renumbered_ops AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS new_id
  FROM public.operators
)
UPDATE public.operators o
SET id = rop.new_id
FROM renumbered_ops rop
WHERE o.id = rop.id;

-- ------------------------------------------------------------------------------
-- 8. Sinkronisasi PostgreSQL Auto-Increment Sequence (setval) ke ID Terakhir
--    Mencegah error 'duplicate key value violates unique constraint' pada data baru.
-- ------------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('public.routes', 'id'), COALESCE((SELECT MAX(id) FROM public.routes), 1));
SELECT setval(pg_get_serial_sequence('public.route_sheets', 'id'), COALESCE((SELECT MAX(id) FROM public.route_sheets), 1));
SELECT setval(pg_get_serial_sequence('public.user_profiles', 'id'), COALESCE((SELECT MAX(id) FROM public.user_profiles), 1));
SELECT setval(pg_get_serial_sequence('public.route_operators', 'id'), COALESCE((SELECT MAX(id) FROM public.route_operators), 1));
SELECT setval(pg_get_serial_sequence('public.operators', 'id'), COALESCE((SELECT MAX(id) FROM public.operators), 1));
SELECT setval(pg_get_serial_sequence('public.roles', 'id'), COALESCE((SELECT MAX(id) FROM public.roles), 1));
SELECT setval(pg_get_serial_sequence('public.daily_route_reports', 'id'), COALESCE((SELECT MAX(id) FROM public.daily_route_reports), 1));
SELECT setval(pg_get_serial_sequence('public.sync_queue_backups', 'id'), COALESCE((SELECT MAX(id) FROM public.sync_queue_backups), 1));

COMMIT;
